Apartments/Controllers/AuthorController.cs
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Apartments.Controllers
{
    public class AuthorController : Controller
    {
        private readonly ModelContainer db = new ModelContainer();
        // GET: Author
        ~AuthorController()
        {
            db.Dispose();
        }
        public ActionResult Index()
        {
            return View(db.Authors);
        }

        // GET: Author/Details/5
        public ActionResult Details(int? id)
        {
            return CommonAction(id);
        }

        private ActionResult CommonAction(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            var author = db.Authors
                .SingleOrDefault(a => a.IdAuthor == id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // GET: Author/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Author/Create
        [HttpPost]
        public ActionResult Create(Author author)
        {
            if (ModelState.IsValid)
            {
                db.Authors.Add(author);
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Author/Edit/5
        public ActionResult Edit(int? id)
        {
            return CommonAction(id);
        }

        // POST: Author/Edit/5
        [HttpPost]
        public ActionResult Edit(int id)
        {
            var author = db.Authors.Find(id);
            if (TryUpdateModel(
                author,
                "",
                new string[]
                {
                    nameof(Author.AuthorName)
                }))
            {

                db.Entry(author).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Author/Delete/5
        public ActionResult Delete(int? id)
        {
            return CommonAction(id);
        }

        // POST: Author/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            foreach (var book in db.Authors.Find(id).Books.ToList())
            {
                db.Authors.Find(id).Books.Remove(book);
            }
            db.Authors.Remove(db.Authors.Find(id));
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Apartments/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace Apartments.Controllers
{
    public class BookController : Controller
    {
        private readonly ModelContainer db = new ModelContainer();
        // GET: Book
        ~BookController()
        {
            db.Dispose();
        }
        public ActionResult Index()
        {
            return View(db.Books);
        }

        // GET: Book/Details/5
        public ActionResult Details(int? id)
        {
            return CommonAction(id);
        }

        private ActionResult CommonAction(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            var book = db.Books
                .Include(a => a.UploadedFiles)
                .SingleOrDefault(a => a.IdBook == id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Book/Create
        public ActionResult Create()
        {
            //List<string> authorNames = db.Authors.Select(a => a.AuthorName).ToList();
            return View();
        }

        // POST: Book/Create
        [HttpPost]
        public ActionResult Create(Book book, IEnumerable<HttpPostedFileBase> files)
        {
            if (ModelState.IsValid)
            {
                book.UploadedFiles = new List<UploadedFile>();
                AddFiles(book, files);
                db.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        // GET: Book/Edit/5
        public ActionResult Edit(int? id)
        {
            return CommonAction(id);
        }

        // POST: Book/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, IEnumerable<HttpPostedFileBase> files)
        {
            var book = db.Books.Find(id);
            if (TryUpdateModel(
                book,
                "",
                new string[]
                {
                    nameof(Book.Title),
                    nameof(Book.Isbn),
                }))
            {
                AddFiles(book, files);

                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        private void AddFiles(Book book, IEnumerable<HttpPostedFileBase> files)
        {
            foreach (var file in files)
            {
                if (file != null && file.ContentLength > 0)
                {
                    var picture = new UploadedFile
                    {
                        ContentType = file.ContentType,
                        Name = file.FileName
                    };
                    using (var reader = new System.IO.BinaryReader(file.InputStream))
                    {
                        picture.Content = reader.ReadBytes(file.ContentLength);
                    }
                    book.UploadedFiles.Add(picture);
                }
            }
        }

        // GET: Book/Delete/5
        public ActionResult Delete(int? id)
        {
            return CommonAction(id);
        }

        // POST: Book/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            db.UploadedFiles.RemoveRange(db.UploadedFiles.Where(f => f.BookIdBook == id));
            db.Books.Remove(db.Books.Find(id));
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Apartments/Controllers/GenreController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Apartments.Controllers
{
    public class GenreController : Controller
    {
        private readonly ModelContainer db = new ModelContainer();
        // GET: Genre
        ~GenreController()
        {
            db.Dispose();
        }
        public ActionResult Index()
        {
            return View(db.Genres);
        }

        // GET: Genre/Details/5
        public ActionResult Details(int? id)
        {
            return CommonAction(id);
        }

        private ActionResult CommonAction(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            var genre = db.Genres
                .SingleOrDefault(a => a.IdGenre == id);
            if (genre == null)
            {
                return HttpNotFound();
            }
            return View(genre);
        }

        // GET: Genre/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Genre/Create
        [HttpPost]
        public ActionResult Create(Genre genre)
        {
            if (ModelState.IsValid)
            {
                db.Genres.Add(genre);
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genre/Edit/5
        public ActionResult Edit(int? id)
        {
            return CommonAction(id);
        }

        // POST: Genre/Edit/5
        [HttpPost]
        public ActionResult Edit(int id)
        {
            var genre = db.Genres.Find(id);
            if (TryUpdateModel(
                genre,
                "",
                new string[]
                {
                    nameof(Genre.GenreName)
                }))
            {

                db.Entry(genre).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genre/Delete/5
        public ActionResult Delete(int? id)
        {
            return CommonAction(id);
        }

        // POST: Genre/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            foreach (var book in db.Genres.Find(id).Books.ToList())
            {
                db.Genres.Find(id).Books.Remove(book);
            }
            db.Genres.Remove(db.Genres.Find(id));
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Apartments/Views/Book/Create.cshtml
@model Apartments.Book

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm(
    "Create", //action
    "Book", //controller
    null, //route values
    FormMethod.Post,
    new { enctype = "multipart/form-data"}
    )) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Book</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Isbn, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Isbn, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Isbn, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Picture", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">

            <input type="file"
                   id="Picture" multiple
                   accept="image/*"
                   name="files" />

        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Apartments/Views/Book/Delete.cshtml
@model Apartments.Book

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdBook)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdBook)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Isbn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Isbn)
        </dd>

        @foreach (var uploadedFile in Model.UploadedFiles)
        {
            <dt>
                @uploadedFile.Name
            </dt>

            <dd style="margin-top:10px">
                <img src="~/File?id=@uploadedFile.IdUploadedFile" alt="Picture"
                     width="300"
                     height="200" />
            </dd>
        }

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Apartments/Views/Book/Details.cshtml
@model Apartments.Book

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdBook)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdBook)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Isbn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Isbn)
        </dd>

        @foreach (var uploadedFile in Model.UploadedFiles)
        {
            <dt>
                @uploadedFile.Name
            </dt>

            <dd style="margin-top:10px">
                <img src="~/File?id=@uploadedFile.IdUploadedFile" alt="Picture"
                     width="300"
                     height="200" />
            </dd>
        }

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdBook }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Apartments/Views/Book/Edit.cshtml
@model Apartments.Book

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm(
    "Edit", //action
    "Book", //controller
    null, //route values
    FormMethod.Post,
    new { enctype = "multipart/form-data" }
    ))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Book</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.IdBook, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IdBook,
           new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Isbn, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Isbn, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Isbn, "", new { @class = "text-danger" })
        </div>
    </div>

    @foreach (var uploadedFile in Model.UploadedFiles)
    {
        <div class="form-group">

            <span class="control-label col-md-2">

                <strong>@uploadedFile.Name</strong> <br />

                @Ajax.ActionLink(
                    "Delete", // text
                    "Delete", // action
                    "File", // controller
                    new { id = uploadedFile.IdUploadedFile },
                    new AjaxOptions()
                    {
                        HttpMethod = "Post"
                    }
               )


            </span>




            <div class="col-md-10">
                <img src="~/File?id=@uploadedFile.IdUploadedFile" alt="Picture"
                     width="300"
                     height="200" />
            </div>

        </div>



    }

    <div class="form-group">
        @Html.Label("Picture", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">

            <input type="file" id="Picture" multiple
                   accept="image/*" name="files" />

        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Apartments/Views/Book/Index.cshtml
@model IEnumerable<Apartments.Book>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New Book", "Create")
    &nbsp;
    @Html.ActionLink("View Authors", "Index", "Author")
    &nbsp;
    @Html.ActionLink("View Genres", "Index", "Genre")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdBook)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Isbn)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdBook)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Isbn)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.IdBook }) |
            @Html.ActionLink("Details", "Details", new { id = item.IdBook }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.IdBook })
        </td>
    </tr>
}

</table>